[package]
name = "todo_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
serde = "1.0.159"
tokio = "1.27.0"
tokio-postgres = "0.7.8"
dotenv = "0.15.0"
